language: objective-c
before_install:
  - brew update
install:
  - brew tap rkrug/experimental
  - brew update
env:
  - PACKAGE=grass-71
script:
  - brew audit $PACKAGE
  - brew install -v $PACKAGE
  - brew test $PACKAGE