language: objective-c
before_install:
  - brew update
install:
  - brew tap rkrug/experimental
  - brew tap homebrew/science
  - brew update
env:
  - PACKAGE=nc_spm_08_grass7 INSTALLOPTIONS=""
  - PACKAGE=grass-71         INSTALLOPTIONS="--HEAD"        
script:
#  - brew audit $PACKAGE
  - brew install $INSTALLOPTIONS $PACKAGE
  - brew test -v $PACKAGE
  - brew uninstall $PACKAGE
