language: objective-c
before_install:
  - brew update
install:
  - brew tap rkrug/experimental
  - brew tap homebrew/science
  - brew update
script:
  - brew audit nc_spm_08_grass7
  - brew install nc_spm_08_grass7
  - brew test -v nc_spm_08_grass7
  - brew uninstall nc_spm_08_grass7
  - brew audit grass-71
  - brew install --HEAD grass-71
  - brew -v test grass-71
  - brew uninstall grass-71