# Author: Rainer Krug, Rainer@krugs.de

# For OS X

os:
       - osx 
       - linux

language:
       - c

compiler:
       - gcc
       - clang
       
before_install:
  - ./.travis.$TRAVIS_OS_NAME.before_install.sh

install:
  - ./.travis.$TRAVIS_OS_NAME.install.sh
  
script:
  - ./.travis.$TRAVIS_OS_NAME.script.sh
  