language: objective-c
before_install:
  - brew update
install:
  - brew tap rkrug/experimental
  - brew tap homebrew/science
  - brew update
env:
  - PACKAGE=nc_spm_08_grass7 INSTALLOPTIONS=""         AUDIT="true"
  - PACKAGE=grass-71         INSTALLOPTIONS="--HEAD"   AUDIT="false"     
script:
  - if [[ "$AUDIT" == "true" ]]; then brew audit -v $PACKAGE; else echo "[SKIPPED] brew audit -v $PACKAGE"; fi
  - brew install $INSTALLOPTIONS $PACKAGE
  - brew test -v $PACKAGE
  - brew uninstall $PACKAGE
