# Author: Rainer Krug, Rainer@krugs.de

language: objective-c

before_install:
  - brew update

install:
  - brew tap rkrug/experimental
  - brew tap rkrug/head-only
  - brew tap rkrug/dev-only
  - brew tap homebrew/science
  - brew update

env:
  - RECIPE=grass-71         INSTALLOPTIONS="--HEAD --with-nc_spm_08_grass7 --with-ffmpeg --with-mysql --with-netcdf --with-postgresql --with-openblas --with-liblas"

script:
  - brew install liblas
  - brew reinstall --build-from-source liblas
  - brew audit -v $RECIPE
  - brew install $INSTALLOPTIONS $RECIPE
  - brew test -v $RECIPE
  - brew info $RECIPE
  - brew uninstall $RECIPE
  