language: objective-c
before_install:
  - brew update
install:
  - brew tap rkrug/experimental
  - brew tap rkrug/head-only
  - brew tap rkrug/dev-only
  - brew tap homebrew/science
  - brew update
env:
  - RECIPE=nc_spm_08_grass7 INSTALLOPTIONS=""
  - RECIPE=grass-71         INSTALLOPTIONS="--HEAD --with-nc_spm_08_grass7"
  - RECIPE=grass-71         INSTALLOPTIONS="--HEAD --with-nc_spm_08_grass7 --with-liblas"
  - RECIPE=grass-71         INSTALLOPTIONS="--HEAD --with-nc_spm_08_grass7 --with-openblas"
script:
  - brew audit -v $RECIPE
  - brew install $INSTALLOPTIONS $RECIPE
  - brew test -v $RECIPE
  - brew info $RECIPE
  - brew uninstall $RECIPE
