# Author: Rainer Krug, Rainer@krugs.de

sudo: required

matrix:
   include:
      - os: linux
        language: c
        compiler: gcc
      - os: linux
        language: c
        compiler: clang
      - os: osx
        compiler: objective-c

before_install:
  - ./.travis.$TRAVIS_OS_NAME.before_install.sh

install:
  - ./.travis.$TRAVIS_OS_NAME.install.sh
  
script:
  - ./.travis.$TRAVIS_OS_NAME.script.sh
  